<h2>1. <code>throw</code> operator</h2>
<p>When an exception is caught by a <code><span class="text-green">catch</span></code> block, and until it is thrown to the Java machine, it is just an object that inherits <code><span class="text-green">Exception</span></code> (or rather, <code>Throwable</code>). <span class="text-red">The exception object itself does not have any magical properties.</span></p>
<p>All the logic of how exceptions work is just a special way the Java machine behaves when an exception is thrown to it.</p>
<p><span class="text-orange">You can always rethrow a caught exception to the Java machine. </span>To do this, you need to use the <code>throw</code> operator:</p>
<div class="lesson-example lesson-example--center">
    <pre class="lecture-code lecture-code--present language-java"><code>throw <span class="text-red">exception</span>;</code></pre>
</div>
<p>Example:</p>
<table>
    <tbody>
    <tr>
        <th>Code</th>
        <th>Console output</th>
    </tr>
    <tr>
        <td>
<pre class="language-java"><code>try
{
   int d = 2/0;
}
catch(<span class="text-viola">Exception</span> <span class="text-red">except</span>)
{
   System.out.println("Caught the exception");
   throw <span class="text-red">except</span>;
}</code></pre>
        </td>
        <td>
            <pre><code>Caught the exception</code></pre>
        </td>
    </tr>
    </tbody>
</table>
<p>In this code, we caught an exception, displayed a message about it on the screen, and then rethrew it.</p>
<p><span class="text-red">A rethrown exception cannot be caught by other <code><span class="text-red">catch</span></code> blocks in the same <code><span class="text-red">try</span></code> block.</span></p>
<hr>
<h2>2. Your exceptions</h2>
<p>By the way, you can create an exception object yourself: <span class="text-green">it is just an object whose type is <code><span class="text-green">Exception</span></code> or a class that inherits it.</span> And throw it.</p>
<p>It's easier than it sounds. Example:</p>
<table>
    <tbody>
    <tr>
        <th>Code</th>
        <th>Console output</th>
    </tr>
    <tr>
        <td>
<pre class="language-java"><code>try
{
   throw new <span class="text-viola">RuntimeException</span>();
}
catch(<span class="text-viola">Exception</span> <span class="text-red">except</span>)
{
   System.out.println("Caught the exception");
   throw <span class="text-red">except</span>;
}</code></pre>
        </td>
        <td>
            <pre><code>Caught the exception</code></pre>
        </td>
    </tr>
    </tbody>
</table>
<p>In the example above, we created a new exception object whose type is <code><span class="text-viola">RuntimeException</span></code> and immediately threw it using the <code>throw</code> operator.</p>
<p>It will be immediately caught by the <code>catch</code> block, since RuntimeException inherits <code><span class="text-viola">Exception</span></code>. The <code>catch (Exception except)</code> code catches exception objects of all classes that inherit the <code><span class="text-viola">Exception</span></code> class.</p>
<hr>
<div class="task-widget-container" showCover="true" taskKey="en.codegym.task.pro.task14.task1406"></div>
<hr>
<h2>3. <code>finally</code> keyword</h2>
<p>Another important point. Sometimes a programmer needs to do perform some action regardless of whether an exception occurred in the code. For example, suppose we opened a file for writing. The opened file <span class="text-viola">must be closed by calling <code><span class="text-viola">close()</span></code>.</span></p>
<pre class="language-java"><code>try
{
   <span class="text-green">// Code where an exception might occur</span>
}
catch(<span class="text-viola">ExceptionType</span> <span class="text-red">name</span>)
{
   <span class="text-user">// Exception handling code</span>
}
finally
{
   <span class="text-viola">// Code that must executed no matter what happens</span>
}</code></pre>
<p>To perform these mandatory actions, another kind of block (<code>finally</code>) was added to the <code>try-catch</code> construct, thereby creating the <code>try-catch-finally</code> construct. It looks like this:</p>
<p>Example:</p>
<pre class="language-java"><code>FileInputStream source = null;
try
{
   source = new FileInputStream("c:\\note.txt");
   source.read();
}
catch(<span class="text-viola">Exception</span> <span class="text-red">except</span>)
{
   System.out.println("Caught the exception");
   throw <span class="text-red">except</span>;
}
finally
{
   if (source != null)
      source.close();
}</code></pre>
<p><span class="text-viola">The code in the <code><span class="text-viola">finally</span></code> block</span> <span class="text-green">will execute in any case, regardless of whether there was an exception.</span> Even if an exception is thrown and not caught, the <code>finally</code> block will still execute.</p>
<p>By the way, if you do not want to catch an exception, but you do need a <code>finally</code> block, use the shorthand notation for the <code>try-catch-finally</code> construct: a <code>try-finally</code> block. It looks something like this:</p>
<div class="lesson-example lesson-example--center">
<pre class="lecture-code lecture-code--present-sm language-java"><code>try
{
   <span class="text-green">// Code where an exception might occur</span>
}
finally
{
   <span class="text-viola">// Code that must executed no matter what happens</span>
}</code></pre>
</div>
<hr>
<div class="task-widget-container" showCover="true" taskKey="en.codegym.task.pro.task14.task1407"></div>